name: github-actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: |
          make install
          pip install pyyaml
      - name: linter
        run: make lint
      - name: run tests
        run: make test
      - name: code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REP_ID }}
        with:
          coverageCommand: make coverage
